### ISSUE TITLE
Improve hook type checking

### ISSUE THREAD

**Issue by Renegade334** [shalture/shalture#47]
Discussion re. `ENSURE_TYPE` which aims to raise compile-time warnings on type mismatch. See below.

Original text, for reference:

> It is only used twice. One is in `include/channels.h`: `ENSURE_TYPE((chan), channel_t *) != NULL` (which can simply be reduced to `chan != NULL`). The other is in `include/mkhooktypes.sh`, where it is supposedly checking the function pointer type passed to the hook, although again doesn't actually do anything.

**Comment by kaniini** [comment]
While `ENSURE_TYPE()` is a hack, it does actually work on clang and some versions of gcc.  The point of it is to induce a compiler warning if the type of the object passed to the hook is wrong.  Thusly I don't think it should be removed.

**Comment by kaniini** [comment]
An alternative idea would be to move the generated macros to proper inline functions, which would provide even stronger type checking.

**Comment by Renegade334** [comment]
Ah yes - my build environment doesn't generate those warnings. I agree that inlining would be better, but there is a problem with declaring inline typechecking functions within `hooktypes.h` as not all of the hook structs are included in the core headers.
